### PR TITLE
Update to latest Apache.NMS.ActiveMQ version

### PR DESCRIPTION
**Pull request by michaelandrepearce**

### CODE REVIEW

**Comment by christopherread** [comment]
Hey @michaelandrepearce thanks for PR, you just need to update the version in a couple more projects for the build to pass:

image

image

**Comment by michaelandrepearce** [comment]
@christopherread thanks didn't see there other references add additional commits to update those to sort.

**Comment by megakid** [comment]
Thanks @michaelandrepearce 

Will get a release out of this soon

**Comment by christopherread** [comment]
@michaelandrepearce should be a new release - v6, which now has NET 5 support - and the code has moved to our new monorepo here:
https://github.com/christopherread/Obvs

**Pull request merged**
